services:
  router:
    build:
      context: ./Router
      dockerfile: Dockerfile
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5229/health"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - "5229:5229"

networks:
  app-network:
    driver: bridge